version: '2.0'

services:

  mysql:
    container_name: sun-finance-mysql
    image: mysql:5
    ports:
        - "3306:3306"
    environment: 
        - MYSQL_ROOT_PASSWORD=sun-finance-root
        - MYSQL_DATABASE=sun-finance-db
    volumes:
       - ./docker-config/mysql/my.cnf:/etc/my.cnf

  phpmyadmin:
    container_name: sun-finance-phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
        - mysql:db
    ports:
        - "8000:80"
    environment:
        - PMA_USER=root
        - PMA_PASSWORD=sun-finance-root
        - PHP_UPLOAD_MAX_FILESIZE=100MB

  web:
    container_name: sun-finance-web
    build: .
    links:
        - mysql
    volumes:
      - ./:/var/www/html:cached
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
